### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jxrloveyou** [JoshuaFeinglass/SMURF#1]
RuntimeError: Failed to import transformers.models.speech_to_text.feature_extraction_speech_to_text because of the following error (look up to see its traceback):
/home1/anaconda3/envs/smurf/lib/python3.9/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
How to solve it？

**Comment by JoshuaFeinglass** [comment]
Hi @jxrloveyou, I have not encountered this issue before, but based on the suggestion from this thread: https://github.com/pytorch/audio/issues/99. I think your environment for pytorch may have been setup incorrectly. It is also possible that the version of pytorch you are using is too old and no longer supported. Try installing from here: https://pytorch.org/get-started/previous-versions/. Be sure to use the conda-specific commands and make sure the pytorch version you install is compatible with cuda and the other libraries.

Let me know if that helps. If you still have issues, comment with the traceback of your error and the versions of the libraries you are using so I can try to reproduce the issue.

**Comment by jxrloveyou** [comment]
@JoshuaFeinglass Thanks for your reply. 
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch
This is my version of these libraries. 
Can you tell me your version of these libraries when you run SMURF?

**Comment by JoshuaFeinglass** [comment]
@jxrloveyou For your convenience, I have added a shell script to quickly install the requirement packages (requirements/install.sh). It will install the latest version of pytorch. Since you are using cuda 10.1, you should change the second line of install.sh accordingly. 

I was able to run SMURF with both pytorch 1.7.1 and the latest version in an Anaconda environment. Your torchaudio issue is unrelated to the SMURF codebase. If you are still having issues after running the installation script, I highly suspect your Anaconda version is outdated. I am using version 4.10.3. A good intermediate test for debugging your environment would be to run 'import torch' separately in a python window.

**Comment by jxrloveyou** [comment]
@JoshuaFeinglass 
Thanks very much for your help, the problem has been solved.
